require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/deploy.rb'
    # below added temporarily to hold back effects of version upgrade
    - 'app/views/search/*'
    - 'lib/tasks/*'

Rails:
  Enabled: true

Lint/UnusedBlockArgument:
  Exclude:
    - 'config/initializers/hydra_config.rb'
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/SymbolProc:
  Exclude:
    - 'spec/factories/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/IndentHash:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/GlobalVars:
  Exclude:
    - 'config/initializers/redis_config.rb'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/jobs/event_jobs_spec.rb'
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'

# disable (temporarily, one hopes?) new cops acquired in the version upgrade
Bundler/OrderedGems:
  Enabled: false

Capybara/CurrentPathExpectation:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentAssignment:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceAroundKeyword:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Lint/UnneededDisable:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'
    - 'Guardfile'

Naming/VariableNumber:
  Enabled: false

Performance/HashEachMethods:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/Blank:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/Present:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/BeEql:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/OverwritingSetup:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OrAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

