require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: '2.3.4'

Rails:
  Enabled: true

Lint/UnusedBlockArgument:
  Exclude:
    - 'config/initializers/hydra_config.rb'
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/jobs/ingest_mets_job.rb'
    - 'app/services/ingest_ephemera_service.rb'
    - 'app/services/ingest_existing_scanned_map.rb'
    - 'app/models/ability.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/indexers/work_indexer.rb'
    - 'app/services/authority_finder.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/indexers/work_indexer.rb'

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/SymbolProc:
  Exclude:
    - 'spec/factories/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/IndentHash:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'


Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/GlobalVars:
  Exclude:
    - 'config/initializers/redis_config.rb'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/jobs/event_jobs_spec.rb'
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
