require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EphemeraFieldsController, type: :controller do
  let(:project) { FactoryGirl.create :ephemera_project }
  let(:vocab) { FactoryGirl.create :vocabulary }
  let(:valid_attributes) { { name: 'EphemeraFolder.language', vocabulary: vocab } }
  let(:invalid_attributes) { { name: 'EphemeraFolder.language' } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EphemeraFieldsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #new" do
    it "assigns a new ephemera_field as @ephemera_field" do
      get :new, params: { ephemera_project_id: project.id }, session: valid_session
      expect(assigns(:ephemera_field)).to be_a_new(EphemeraField)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ephemera_field as @ephemera_field" do
      ephemera_field = EphemeraField.create! valid_attributes
      get :edit, params: { id: ephemera_field.to_param, ephemera_project_id: project.id }, session: valid_session
      expect(assigns(:ephemera_field)).to eq(ephemera_field)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new EphemeraField" do
        expect {
          post :create, params: { ephemera_field: valid_attributes, ephemera_project_id: project.id }, session: valid_session
        }.to change(EphemeraField, :count).by(1)
      end

      it "assigns a newly created ephemera_field as @ephemera_field" do
        post :create, params: { ephemera_field: valid_attributes, ephemera_project_id: project.id }, session: valid_session
        expect(assigns(:ephemera_field)).to be_a(EphemeraField)
        expect(assigns(:ephemera_field)).to be_persisted
      end

      it "redirects to the created ephemera_field" do
        post :create, params: { ephemera_field: valid_attributes, ephemera_project_id: project.id }, session: valid_session
        expect(response).to redirect_to(ephemera_project_url(project))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ephemera_field as @ephemera_field" do
        post :create, params: { ephemera_field: invalid_attributes, ephemera_project_id: project.id }, session: valid_session
        expect(response).not_to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { { name: 'EphemeraFolder.genre', vocabulary: vocab } }

      it "updates the requested ephemera_field" do
        ephemera_field = EphemeraField.create! valid_attributes
        put :update, params: { id: ephemera_field.to_param, ephemera_field: new_attributes, ephemera_project_id: project.id }, session: valid_session
        ephemera_field.reload
        expect(ephemera_field.name).to eq('EphemeraFolder.genre')
      end

      it "assigns the requested ephemera_field as @ephemera_field" do
        ephemera_field = EphemeraField.create! valid_attributes
        put :update, params: { id: ephemera_field.to_param, ephemera_field: valid_attributes, ephemera_project_id: project.id }, session: valid_session
        expect(assigns(:ephemera_field)).to eq(ephemera_field)
      end

      it "redirects to the ephemera_field" do
        ephemera_field = EphemeraField.create! valid_attributes
        put :update, params: { id: ephemera_field.to_param, ephemera_field: valid_attributes, ephemera_project_id: project.id }, session: valid_session
        expect(response).to redirect_to(ephemera_project_url(project))
      end
    end

    context "with invalid params" do
      it "assigns the ephemera_field as @ephemera_field" do
        ephemera_field = EphemeraField.create! valid_attributes
        put :update, params: { id: ephemera_field.to_param, ephemera_field: invalid_attributes, ephemera_project_id: project.id }, session: valid_session
        expect(response).not_to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ephemera_field" do
      ephemera_field = EphemeraField.create! valid_attributes
      expect {
        delete :destroy, params: { id: ephemera_field.to_param, ephemera_project_id: project.id }, session: valid_session
      }.to change(EphemeraField, :count).by(-1)
    end

    it "redirects to the ephemera_fields list" do
      ephemera_field = EphemeraField.create! valid_attributes
      delete :destroy, params: { id: ephemera_field.to_param, ephemera_project_id: project.id }, session: valid_session
      expect(response).to redirect_to(ephemera_project_url(project))
    end
  end
end
