require 'vocab/pul_terms'

# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior

  property :exhibit_id, predicate: ::PULTerms.exhibit_id, multiple: false do |index|
    index.as :stored_searchable, :symbol
  end

  validates :exhibit_id, presence: true
  validates_with ExhibitIdValidator
end
