require 'vocab/pul_terms'

# Generated by hyrax:models:install
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  include Hyrax::BasicMetadata
  include ::CollectionTitleIndexing
  include ::DefaultReadGroups

  def self.human_readable_short_description
  end

  property :exhibit_id, predicate: ::PULTerms.exhibit_id, multiple: false do |index|
    index.as :stored_searchable, :symbol
  end

  validates :exhibit_id, presence: true
  validates_with ExhibitIdValidator

  def first_title
    title.first
  end
end
