# Generated by curation_concerns:models:install
class GenericFile < ActiveFedora::Base
  include ::CurationConcerns::GenericFileBehavior
  apply_schema IIIFPageSchema

  validates_with ViewingHintValidator
end
