# Generated by curation_concerns:models:install
class GenericFile < ActiveFedora::Base
  include ::CurationConcerns::GenericFileBehavior
  Hydra::Derivatives.output_file_service = PersistPairtreeDerivatives

  apply_schema IIIFPageSchema, ActiveFedora::SchemaIndexingStrategy.new(
    ActiveFedora::Indexers::GlobalIndexer.new([:stored_searchable, :symbol])
  )

  validates_with ViewingHintValidator
  makes_derivatives :create_intermediate_file

  def iiif_path
    IIIFPath.new(id).to_s
  end

  private

    def create_intermediate_file
      case original_file.mime_type
      when 'image/tiff'
        transform_file :original_file, {
          service: {
            datastream: 'intermediate_file',
            recipe: :default
          }
        }, processor: 'jpeg2k_image'
      end
    end
end
